---
# tasks file for wdijkerman.zabbix-web

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install the correct repository"
  include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
  tags:
    - zabbix-web

- name: "Install the correct repository"
  include: "Debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - zabbix-web

- name: "Create zabbix-web directory"
  file:
    path: /etc/zabbix/web
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    state: directory
    mode: 0755
  tags:
    - zabbix-web
    - init
    - config

- name: "Configure zabbix-web"
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0644
  notify:
    - restart nginx
  tags:
    - zabbix-web
    - init
    - config
