---
# Tasks specific for RedHat systems

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  tags:
    - zabbix-web
    
- name: Install remi repository
  shell: rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    
- name: "RedHat | Install yum-utils"
  yum:
    pkg: yum-utils
    state: present
  tags:
    - yum-utils
    
- name: Configure php version
  shell: yum-config-manager --enable remi-php70
    
- name: "RedHat | Install zabbix-web-{{ database_type }}"
  yum:
    pkg: zabbix-web-{{ database_type }}
    state: present
  tags:
    - zabbix-web
    
- name: "RedHat | install nginx vhost"
  template:
    src: nginx_vhost.conf.j2
    dest: /etc/nginx/sites-available/zabbix.conf
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0644
  when: zabbix_vhost
  notify:
    - restart nginx
  tags:
    - zabbix-web
    - init
    - config
    - nginx

- name: "RedHat | enable nginx vhost"
  file:
    src: /etc/nginx/sites-available/zabbix.conf
    dest: /etc/nginx/sites-enabled/zabbix.conf
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    state: link
  when: zabbix_vhost
  notify:
    - restart nginx
  tags:
    - zabbix-server
    - init
    - config
    - nginx
